server:
  port: 9000
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: lms
    password: 1234
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations:
  - classpath:mapper/**/*.xml